# Generated by Django 5.2.8 on 2026-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_blocked_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reaction',
            field=models.CharField(choices=[('none', 'No Reaction'), ('up', 'Thumbs Up'), ('down', 'Thumbs Down')], default='none', max_length=10),
        ),
    ]
